### ISSUE TITLE
[HW] K S A R AMBEDKAR

### ISSUE THREAD

**Issue by ambedkar1985** [datastaxdevs/workshop-graphql-netflix#126] opened 2021-06-13 10:28 UTC
**Name:** K S A R AMBEDKAR
**Email:** ambedkar1985@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/k-s-a-r-ambedkar-50b12088/

Attach the homework screenshots below:
[[HW]-Assign . of Netflix live.pdf](https://github.com/datastaxdevs/workshop-graphql-netflix/files/6643702/HW.-Assign.of.Netflix.live.pdf)

**Comment by clun** [comment] 2021-06-15 06:49
duplicate of the #125 will just close this one

**Closed by clun** 2021-06-15 06:49 UTC
Labels: homework, wait for review
