### ISSUE TITLE
[HW] Netflix Clone:GP

### ISSUE THREAD

**Issue by gayatripandya** [datastaxdevs/workshop-graphql-netflix#246] opened 2021-07-02 14:08 UTC
**Name:** Gayatri Pandya
**Email:** gayatripandya69@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/gayatri-p-0b0095bb

Attach the homework screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/55309633/124096502-46948000-da78-11eb-911c-fd8436d35fe6.png)

![image](https://user-images.githubusercontent.com/55309633/124096620-61ff8b00-da78-11eb-8db2-a8bf02164a84.png)

![image](https://user-images.githubusercontent.com/55309633/124096698-72176a80-da78-11eb-8907-f98fcab23144.png)

![image](https://user-images.githubusercontent.com/55309633/124270711-31901d80-db5a-11eb-9be7-fed785b63ce9.png)

Here is the movie I added:"10 Things I Hate About You":

![image](https://user-images.githubusercontent.com/55309633/124286361-7c1a9580-db6c-11eb-80c4-f42a573825f0.png)
![image](https://user-images.githubusercontent.com/55309633/124286467-9b192780-db6c-11eb-9517-eff60b693eb3.png)

**Comment by SonicDMG** [comment] 2021-07-04 02:01
Hi again. This looks like a duplicate of https://github.com/datastaxdevs/workshop-graphql-netflix/issues/196 and I issues your badge there. I will close this out. Thank you.

**Closed by SonicDMG** 2021-07-04 02:01 UTC
Labels: homework, wait for review
