### ISSUE TITLE
[HW] <Madhurima Paul>

### ISSUE THREAD

**Issue by MadhurimaPaul-87** [datastaxdevs/workshop-graphql-netflix#280] opened 2021-07-07 01:23 UTC
**Name:** <Madhurima Paul>
**Email:** <mguharoy4@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/madhurima-paul-67924b82/>

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

![Screenshot 2021-07-07 064514](https://user-images.githubusercontent.com/79975103/124685495-022d3800-deef-11eb-8fbe-4726e4e201ff.png)

**Comment by SonicDMG** [comment] 2021-07-09 17:57
Hi there Madhurima, thank you for your submission. I see you deployed the app with Netlify, great, but I do not see an image of a custom video in your app per step 2 of the homework.
2. Insert a movie of your choice in the database.

Please insert a custom video and post a screenshot.

**Comment by SonicDMG** [comment] 2021-07-09 18:05
Duplicate of https://github.com/datastaxdevs/workshop-graphql-netflix/issues/281

**Closed** 2021-07-09 18:06 UTC
Labels: duplicate, homework
